# -*- mode: ruby -*-
# vi: set ft=ruby :
# /var/www/html/

RAM = 1024
CPU = 1
IP = "10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "hamza-dev/ubuntu-nginx-mysql-composer"
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: IP
  config.vm.hostname = "nginx"
  config.vm.synced_folder "src/", "/usr/share/nginx/html/"
	config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
  end

end
